# Generated by Django 5.2.7 on 2025-11-02 06:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cover', models.ImageField(blank=True, upload_to='covers/')),
                ('year_published', models.IntegerField()),
                ('lnaguage', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('source_of_collection', models.CharField(max_length=200)),
                ('book_number', models.CharField(max_length=50, unique=True)),
                ('shelf_location', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('num_of_copies', models.IntegerField(default=1)),
                ('num_of_time_borrowed', models.IntegerField(default=0)),
                ('last_borrowed_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=300)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookInfo.book')),
            ],
        ),
    ]
