"""
Django settings for lmsProject project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""
import os
from decouple import config
from pathlib import Path



# -------------------------------------------------------------------
# BASE SETUP
# -------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# -------------------------------------------------------------------
# SECURITY
# -------------------------------------------------------------------
SECRET_KEY = config("THE_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG_MODE", cast = bool)

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]   #new 

# -------------------------------------------------------------------
# AUTHENTICATION
# -------------------------------------------------------------------
AUTH_USER_MODEL = "accounts.CustomUser"

# -------------------------------------------------------------------
#  To Use Allauth
# -------------------------------------------------------------------
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_REDIRECT_URL = "home"
ACCOUNT_LOGOUT_REDIRECT_URL = "home"

ACCOUNT_SESSION_REMEMBER = True     #new

ACCOUNT_FORMS = {
    'signup': 'accounts.forms.CustomSignupForm',
}                                                   #new We are using custom signup form 

# -------------------------------------------------------------------
# EMAIL (Console for development)
# -------------------------------------------------------------------
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"



# -------------------------------------------------------------------
#  APPLICATIONS
# -------------------------------------------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 3rd Party
    'crispy_forms', # new
    'crispy_bootstrap5', # new
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    
    #local 
    'accounts.apps.AccountsConfig',
    'pages.apps.PagesConfig'
]


# To use crispy
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# -------------------------------------------------------------------
#  To Use Allauth
# -------------------------------------------------------------------
ACCOUNT_FORMS = {
    'signup': 'accounts.forms.CustomSignupForm',
}                                                   #new We are using custom signup form 

""" old Version
ACCOUNT_USERNAME_REQUIRED = False # new
ACCOUNT_AUTHENTICATION_METHOD = "email" # new
ACCOUNT_EMAIL_REQUIRED = True # new
ACCOUNT_UNIQUE_EMAIL = True # new
"""
""" To make Emain mendatory 
ACCOUNT_LOGIN_METHODS = {"email"}

ACCOUNT_UNIQUE_EMAIL = True  # <— ensures unique email
ACCOUNT_EMAIL_VERIFICATION = "optional"  # or "mandatory" if you want email confirmation
"""

# -------------------------------------------------------------------
# MIDDLEWARE
# -------------------------------------------------------------------

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # Add the account middleware:
    "allauth.account.middleware.AccountMiddleware",
]



# -------------------------------------------------------------------
# URL & WSGI
# -------------------------------------------------------------------
ROOT_URLCONF = 'lmsProject.urls'
WSGI_APPLICATION = 'lmsProject.wsgi.application'



# -------------------------------------------------------------------
# TEMPLATES 
# -------------------------------------------------------------------

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR /'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # `allauth` needs this from django
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"



# -------------------------------------------------------------------
# DATABASES 
# -------------------------------------------------------------------

"""DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}"""

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config("DB_NAME"),
        'USER': config("DB_USER"),
        'PASSWORD': config("DB_PASSWORD"),
        'HOST': config("HOST"),
        'PORT': config("PORT"),  # use your PostgreSQL port
    }
}



# -------------------------------------------------------------------
# PASSWORD VALIDATIONS
# -------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# -------------------------------------------------------------------
# INTERNATIONALIZATION
# -------------------------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "America/New_York"
USE_I18N = True
USE_TZ = True



# -------------------------------------------------------------------
# STATIC FILES
# -------------------------------------------------------------------
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage" # new
# command to collect static file : python3 manage.py collectstatic


# -------------------------------------------------------------------
# DEFAULT PRIMARY KEY
# -------------------------------------------------------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
